### ISSUE TITLE
Erro na integração Mockery + PHPUnit

### ISSUE THREAD

**Issue by guilhermeyoshida** [devfullcycle/FC3-admin-catalogo-de-videos-php#1]
Estou incapacitado de executar o test https://github.com/devfullcycle/FC3-admin-catalogo-de-videos-php/blob/main/tests/Unit/UseCase/Category/CreateCategoryUseCaseUnitTest.php#L15-L53.

Ao declarar as variáveis privadas `$this->mockEntity, $this->mockRepo, $this->mockInputDto, etc`. Meu compilador acusa: `Undefined property '$mockEntity'.intelephense(1014)`.

Um workaround foi cria-las na classe, porém o `$this->mockEntity->shouldReceive` também não é encontrado: `Undefined method 'shouldReceive'.intelephense(1013)`.

Meu composer.json: 
`
{
    "name": "root/www",
    "autoload": {
        "psr-4": {
            "Core\\": "src/Core/"
        }
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5",
        "mockery/mockery": "^1.5"
    },
    "require": {
        "ramsey/uuid": "^4.7"
    }
}
`

phpunit.xml: 
`<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         colors="true">
    <testsuites>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>
    </testsuites>
    <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">./app</directory>
        </include>
    </coverage>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="BCRYPT_ROUNDS" value="4"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
        <env name="MAIL_MAILER" value="array"/>
        <env name="QUEUE_CONNECTION" value="sync"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="TELESCOPE_ENABLED" value="false"/>
        <env name="FILESYSTEM_DISK" value="local"/>
    </php>
</phpunit>`

`$ composer info | grep mockery`
`mockery/mockery                    1.5.1   Mockery is a simple yet flexible PHP mock object framework`

**Comment by carlosfgti** [comment]
Opa, eae tudo bem?

Satisfação falar com você.

Sempre que tiver qualquer problema, pode abrir um novo tópico no fórum, que terei o maior prazer em te ajudar.

Para este caso, gravei uma aula sobre o assunto, aqui está: [AULA](https://plataforma.fullcycle.com.br/courses/183/168/142/conteudos?capitulo=142&conteudo=7971)
